### ISSUE TITLE
Reusable interaction system component

### ISSUE THREAD

**Issue by SeanTSinclair** [SeanTSinclair/GameOff2024#25]
A reusable component that can be re-used on all interactable components in the game. 

Key functions
A flag which indicates that it is currently able to interact with: isInteractable::bool
Press <Any Key::Configurable> to interact
Interact Looks through the children for an or multiple nodes of type Interactable and calls the Interact() function

We can then create for example a LockpickingInteractable which on Interact brings forth a lockpicking screen and disables input controlling the player etc.

**Comment by bakkelim** [comment]
I've used this as a reference in another project: https://www.youtube.com/watch?v=ajCraxGAeYU&t=27s&ab_channel=DashNothing

**Comment by bakkelim** [comment]
For those who are interested:
I ended up implementing based on this video: https://www.youtube.com/watch?v=QKdyUBjzPmk&t=56s&ab_channel=Nagi

As the first video I linked is more for 2D games where you have a lot of intractable objects around you, while in first person 3D you are looking directly at object.
